nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

enableImmutableInstalls: false

nmSelfReferences: false

logFilters:
  - pattern: "* provides react *"
    level: discard
  - pattern: "* provides react-dom *"
    level: discard
  - pattern: "* provides graphql *"
    level: discard
  - pattern: "* doesn't provide react *"
    level: discard
  - pattern: "* doesn't provide react-dom *"
    level: discard
  - pattern: "* doesn't provide webpack *"
    level: discard
  - pattern: "* doesn't provide @babel/core *"
    level: discard
  - pattern: "* doesn't provide graphql *"
    level: discard
