name: "Mock Tests"
description: "Run mock tests"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install
      working-directory: test
      shell: bash
    - run: mv macOS-replay-playwright/macOS-replay-playwright.tar.xz ./
      shell: bash
    - run: tar xf ./macOS-replay-playwright.tar.xz
      shell: bash
    - run: chmod +x ./firefox/Nightly.app/Contents/MacOS/firefox
      shell: bash
    - run: node ${{ github.action_path }}/../../../test/mock/run.js
      shell: bash
      env:
        DEBUG: "pw:api"
