name: "Mock Tests"
description: "Run mock tests"
runs:
  using: "composite"
  steps:
    # Get the yarn cache path.
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
    - name: Restore yarn cache
      uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **/node_modules
        key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
        restore-keys: "yarn-cache-folder-"
    # Actually install packages with Yarn
    - name: Install packages
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install
      shell: bash
      env:
        YARN_CHECKSUM_BEHAVIOR: "update"
    - run: mv macOS-replay-playwright/macOS-replay-playwright.tar.xz ./
      shell: bash
    - run: tar xf ./macOS-replay-playwright.tar.xz
      shell: bash
    - run: chmod +x ./firefox/Nightly.app/Contents/MacOS/firefox
      shell: bash
    - run: node ${{ github.action_path }}/../../../test/mock/run.js
      shell: bash
