steps:
  - label: "Runtime e2e tests (linux-x86_64)"
    if: (build.env("OS") == "linux" && build.env("ARCH") == "x86_64") || (build.env("OS") == null && build.env("ARCH") == null)
    timeout_in_minutes: 60
    commands:
      - "mkdir -p /mnt/data/replay"
      - "be_cmd node_deps -- npx yarn install"
      - "be_cmd run_tests -- ts-node ./packages/e2e-tests/scripts/buildkite_run_tests_from_reason-linux-x86_64.ts"
    agents:
      - "e2e=true"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: us-east-2
          env:
            AUTOMATED_TEST_SECRET: "graphql-automated-test-secret"
            RECORD_REPLAY_API_KEY: "runtime-record-replay-api-key"
            HASURA_ADMIN_SECRET: "prod/hasura-admin-secret"
            AWS_ACCESS_KEY_ID:
              secret-id: "prod/build-user"
              json-key: ".access_key_id"
            AWS_SECRET_ACCESS_KEY:
              secret-id: "prod/build-user"
              json-key: ".secret_access_key"
            RUNTIME_TEAM_API_KEY: runtime-replay-api-key
            BUILDEVENT_APIKEY: honeycomb-api-key
            BUILDEVENT_BUILDKITE_API_TOKEN: buildkite-api-token-honeycomb-build-events
      - replayio/buildevents#0c2adb2: ~
    env:
      DISPLAY: ":99"
      PLAYWRIGHT_HEADLESS: "true"
      PLAYWRIGHT_CHROMIUM: "true"
      RECORD_REPLAY_DIRECTORY: "/mnt/data/replay"
      AWS_DEFAULT_REGION: "us-east-2"

  - label: "Runtime e2e tests (macos-arm64)"
    if: build.env("OS") == "macos" && build.env("ARCH") == "arm64"
    timeout_in_minutes: 60
    commands:
      - "be_cmd node_deps -- npx yarn install"
      - "be_cmd run_tests -- ts-node ./packages/e2e-tests/scripts/buildkite_run_tests_from_reason-macos-arm64.ts"
    agents:
      - "os=macos"
      - "arch=arm64"
      - "queue=runtime"
      - "runtimeType=test"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: us-east-2
          env:
            BUILDKITE_AGENT_TOKEN: "prod/buildkite-agent-token"
            AUTOMATED_TEST_SECRET: "graphql-automated-test-secret"
            RECORD_REPLAY_API_KEY: "runtime-record-replay-api-key"
            HASURA_ADMIN_SECRET: "prod/hasura-admin-secret"
            RUNTIME_TEAM_API_KEY: runtime-replay-api-key
            BUILDEVENT_APIKEY: honeycomb-api-key
            BUILDEVENT_BUILDKITE_API_TOKEN: buildkite-api-token-honeycomb-build-events
      - replayio/buildevents#0c2adb2: ~
    env:
      DISPLAY: ":1"
      PLAYWRIGHT_HEADLESS: "true"
      PLAYWRIGHT_CHROMIUM: "true"
      ARCHITECTURE: "arm64"
