name: "npm install"
description: "Installs dependencies from npm, with caching"
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: "npm"
    - name: Install dependencies
      run: npm ci
      shell: bash
