name: "Tests: Playwright"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
  FLAKINESS_CONNECTION_STRING: ${{ secrets.FLAKINESS_CONNECTION_STRING }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print job info
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          node --version
      - name: Check out repository code
        uses: actions/checkout@v2
      # Get the yarn cache path.
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Restore yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: "yarn-cache-folder-"
      # Actually install packages with Yarn
      - name: Install packages
        run: yarn install
        shell: bash
        working-directory: packages/bvaughn-architecture-demo
      - uses: supplypike/setup-bin@v1
        with:
          uri: 'https://github.com/earthly/earthly/releases/download/v0.6.14/earthly-linux-amd64'
          name: 'earthly'
          version: '0.6.14'
      - name: Earthly version
        run: earthly --version
      - name: Run dev server and Playwright tests
        run: ./playwright.js
        working-directory: packages/bvaughn-architecture-demo
      - name: Archive trace artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Playwright test results
          path: packages/bvaughn-architecture-demo/playwright/test-results
      - name: Upload results
        run: ./uploadSnapshots.js
        working-directory: packages/bvaughn-architecture-demo
