name: GraphQL

on: [pull_request, workflow_dispatch]

jobs:
  gql_codegen:
    name: GraphQL codegen check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Deps
        run: npm install
      - name: Fetch the schema
        run: npm run gql:schema
      - name: Codegen
        run: npm run gql:codegen
      - name: Checks if types match
        run: git diff origin/master --quiet
