on:
  push:
    branches:
      - 'main'

jobs:
  mirror_job:
    runs-on: blacksmith
    name: Mirror main branch to staging branch
    steps:
    - name: Mirror action step
      id: mirror
      uses: google/mirror-branch-action@v1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        source: 'main'
        dest: 'staging'