name: Nightly
on:
  schedule:
    - cron: 0 8 * * 1-5
  workflow_dispatch:

jobs:
  trunk_check:
    name: Trunk Check Upload
    runs-on: blacksmith

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.0.0
        with:
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
